 create table employee_table (
        employee_id INTEGER GENERATED BY DEFAULT ON NULL AS IDENTITY,
        email varchar(255),
        employee_name varchar(255),
        salary number,
        primary key (employee_id)
    );